<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="<?=BASE_URL.'styles/reset.css'?>">
    <link rel="stylesheet" href="<?=BASE_URL.'styles/style.css'?>">
    <link rel="stylesheet" href="<?=BASE_URL.'styles/addUsers.css'?>">
    <link rel="stylesheet" href="<?=BASE_URL.'styles/create--account.css'?>">
    <link rel="stylesheet" href="<?=BASE_URL.'styles/login.css'?>">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <title>Connexion</title>
</head>
<body>