        </div>
    </div>
    <script src="<?=BASE_URL.'dist/js/jquery-3.6.0.min.js'?>"></script>
    <script src="<?=BASE_URL.'dist/js/bootstrap.min.js'?>"></script>
    <script src="<?=BASE_URL.'dist/js/bootstrap.bundle.min.js'?>"></script>
    <script src="<?=BASE_URL.'dist/js/script.js'?>"></script>
    <script>
        $('#pills-tab a').on('click', function (e) {
            e.preventDefault()
            $(this).tab('show')
        })
    </script>
  </body>
</html>