<?php 
    if(!($_SESSION['connect'] && $_SESSION['token'])){
        header('location:?p=login');
    }
?>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="<?=BASE_URL.'styles/reset.css'?>">
    <link rel="stylesheet" href="<?=BASE_URL.'styles/sidebar.css'?>">
    <link rel="stylesheet" href="<?=BASE_URL.'styles/style.css'?>">
    <link rel="stylesheet" href="<?=BASE_URL.'styles/home.css'?>">
    <link rel="stylesheet" href="<?=BASE_URL.'styles/users.css'?>">
    <link rel="stylesheet" href="<?=BASE_URL.'styles/avis.css'?>">
    <link rel="stylesheet" href="<?=BASE_URL.'styles/searcbox.css'?>">
    <link rel="stylesheet" href="<?=BASE_URL.'styles/login.css'?>">
    <link rel="stylesheet" href="<?=BASE_URL.'styles/addUsers.css'?>">
    <link rel="stylesheet" href="<?=BASE_URL.'styles/create--account.css'?>">
    <title>Dashboard</title>

    <script>
      let headers = {
        "Content-Type": "application/json",
        "Api-Key": <?php echo json_encode(APIKEY); ?>,
        "Authorization": <?php echo json_encode($_SESSION['token']); ?>
      }
    </script>

    <script>
      let url = <?php echo json_encode(API_URL); ?>;
    </script>
</head>
<body>
        <div class="top__menu">
          <div class="top__menu__nav">
              <div class="nav__list">
                 
              </div>
              <div class="nav__list">
                <li class="nav__list__li"><a href="#">JODGE</a></li>
                <li class="nav__list__li"><a href="controllers/logout.php">Déconnexion</a></li>
              </div>
          </div>
        </div>
        <div class="main-menu__block__searchbox">
            <div class="main-menu__block__searchbox__container">
                <h2>Hakennals</h2>
                <div class="main-menu__block__searchbox--content-flex">
                    <h2>Entité :</h2>
                    <input class="main-menu__block__searchbox__input" type="text" name="text" class="search" placeholder="">
                </div>
                <div class="main-menu__block__searchbox--content-flex">
                    <h2>Recherche :</h2>
                    <input class="main-menu__block__searchbox__input" type="text" name="text" class="search" placeholder="">
                </div>
                <div class="main-menu__block__searchbox--content-flex--3">
                    <h2>Références :</h2>
                    <div>
                        <input class="main-menu__block__searchbox__input--3" type="text" name="text" class="search" placeholder="">
                        <input class="main-menu__block__searchbox__input--3" type="text" name="text" class="search" placeholder="">
                    </div>
                </div>
                <a href="?p=dashboard" class="back--to-home">Retourner à l'accueil</a>
            </div>
        </div>