<section>
        <div class="container--create__account">
            <div class="home__add-users">
                <div class="home__content__create__account">
                    <div class="form__container">
                        <form id="create">
    
                            <div class="form__title">
                                <p><br/><br/><br/><br/></p>
                                <h2>Créer un nouveau client</h2>
                            </div>
                            <p class="center message"></p>
                          <div class="label__container">
                            <label for="fname">Nom complet (*):</label>
                            <input class="input__add-users require" type="text" id="fullname" name="firstname" placeholder="Nom complet..">
                          </div> 
                      
                          <div class="label__container">
                            <label for="fname">Pseudo :</label>
                            <input class="input__add-users" type="text" id="pseudo" name="firstname" placeholder="Pseudo..">
                          </div>
    
                          <div class="label__container">
                            <label for="fname">Téléphone (*) :</label>
                            <input class="input__add-users require" type="text" id="phone" name="firstname" placeholder="Téléphone..">
                          </div>

                          <div class="label__container">
                            <label for="fname">Email :</label>
                            <input class="input__add-users" type="text" id="email" name="firstname" placeholder="Email..">
                          </div>

                          <div class="label__container">
                            <label for="sexe">Genre (*):</label>
                            <select name="" id="sexe" class="input__add-users require">
                                <option value=""></option>
                                <option value="H">Homme</option>
                                <option value="F">Femme</option>
                            </select>
                          </div>
                         
                            <div class="create__account-btn">
                                <button type="submit">Inscrire</button>
                                <br><br><br>
                            </div>
                        </form>
                      </div> 
                </div>
              </div>
        </div>
    </section>