<?php 
    if($_SESSION['usr_hetic']){
        header('location:?p=dashboard');
    }
?>
<section>
    <div class="container--create__account">
        <div class="home__add-users">
            <div class="home__content__login">
                <div class="form__container">
                    <form>

                        <div class="form__title">
                            <p>Customotel API</p>
                            <h2>Connectez-vous</h2>
                        </div>
                    
                        <div class="label__container">
                        <p class="center retour"></p>
                        <div class="label__container">
                        <label for="fname">Adresse mail :</label>
                        <input class="input__add-users" type="text" id="fname" name="firstname" placeholder="Email">
                        </div>

                        <div class="label__container">
                        <label for="fname">Mot de passe :</label>
                        <input class="input__add-users" type="password" id="fname" name="firstname" placeholder="mot de passe">
                        </div>
                        <div class="block__login-btn">
                        <button class="btn-login">Se connecter</button>
                        </div>

                        <hr class="login--separator">

                        <p class="not__register--text">Vous n'avez pas de compte ? <a class="button__not-register" href="create-account.html">Créez en un !</a></p>
                        
                    </form>
                </div> 
            </div>
        </div>
    </div>
</section>

