<?php 
    if($_SESSION['connect'] && $_SESSION['token']){
        header('location:?p=dashboard');
    }
?>
<section>
    <div class="container--create__account">
        <div class="home__add-users">
            <div class="home__content__login">
                <div class="form__container">
                    <form>

                        <div class="form__title">
                            <p>Customotel API</p>
                            <h2>Connectez-vous</h2>
                        </div>
                    
                        <div class="label__container">
                        <p class="center message"></p>
                        <div class="label__container">
                        <label for="inputEmail">Adresse mail :</label>
                        <input class="input__add-users require" type="text" id="inputEmail"  placeholder="Email">
                        </div>

                        <div class="label__container">
                        <label for="inputPassword">Mot de passe :</label>
                        <input class="input__add-users require" type="password" id="inputPassword"  placeholder="mot de passe">
                        </div>
                        <div class="block__login-btn">
                        <button class="btn-login" id="submit">Se connecter</button>
                        </div>

                        <hr class="login--separator">
                    </form>
                </div> 
            </div>
        </div>
    </div>
</section>

